require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventsController do
  context 'a guest' do
    before do
      get :index
    end

    it { should deny_access }
  end

  context 'a user' do
    before do
      sign_in
    end

    let(:owner) { FactoryGirl.create(:user) }
    let(:category) { FactoryGirl.create(:category) }

    let(:valid_attributes) do
      FactoryGirl.attributes_for(:event).merge(owner_id: owner.id, category_id: category.id)
    end

    let(:valid_session) { {} }

    describe "GET index" do
      it "assigns all events as @events" do
        event = FactoryGirl.create(:event)
        get :index, {}, valid_session
        expect(assigns(:events)).to eq([event])
      end

      it 'assigns all the categories of the events as @categories' do
        category1 = FactoryGirl.create(:category, identifier: :red)
        category2 = FactoryGirl.create(:category, identifier: :yellow)
        FactoryGirl.create(:event, category: category2, starts: Time.current - 24.hours)
        FactoryGirl.create(:event, category: category1)

        get :index, {}, valid_session
        expect(assigns(:categories)).to eq([category1])
      end

      context 'without a date selected' do
        it 'assigns the current date as selection' do
          get :index, {}, valid_session
          expect(assigns(:selected_date)).to eq(Date.current)
        end
      end

      context 'with an invalid date selected' do
        it 'assigns the current date as selection' do
          get :index, { date: 'asd' }, valid_session
          expect(assigns(:selected_date)).to eq(Date.current)
        end
      end

      context 'with an valid date selected' do
        it 'assigns the current date as selection' do
          get :index, { date: '2014-04-01' }, valid_session
          expect(assigns(:selected_date)).to eq(Date.new(2014,4,1))
        end
      end
    end

    describe "GET show" do
      it "assigns the requested event as @event" do
        event = Event.create! valid_attributes
        get :show, {:id => event.to_param}, valid_session
        expect(assigns(:event)).to eq(event)
      end
    end

    describe "GET new" do
      it "assigns a new event as @event" do
        get :new, {}, valid_session
        expect(assigns(:event)).to be_a_new(Event)
      end
    end

    describe "GET edit" do
      it "assigns the requested event as @event" do
        event = Event.create! valid_attributes
        get :edit, {:id => event.to_param}, valid_session
        expect(assigns(:event)).to eq(event)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Event" do
          expect {
            post :create, {:event => valid_attributes}, valid_session
          }.to change(Event, :count).by(1)
        end

        it "assigns a newly created event as @event" do
          post :create, {:event => valid_attributes}, valid_session
          expect(assigns(:event)).to be_a(Event)
          expect(assigns(:event)).to be_persisted
        end

        it "redirects to the created event" do
          post :create, {:event => valid_attributes}, valid_session
          expect(response).to redirect_to(Event.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved event as @event" do
          # Trigger the behavior that occurs when invalid params are submitted
          allow_any_instance_of(Event).to receive(:save).and_return(false)
          post :create, {:event => { "owner" => "invalid value" }}, valid_session
          expect(assigns(:event)).to be_a_new(Event)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          allow_any_instance_of(Event).to receive(:save).and_return(false)
          post :create, {:event => { "owner" => "invalid value" }}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested event" do
          event = Event.create! valid_attributes
          # Assuming there are no other events in the database, this
          # specifies that the Event created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          expect_any_instance_of(Event).to receive(:update).with({ 'owner_id' => owner.id.to_s })
          put :update, {:id => event.to_param, :event => { owner_id: owner.id }}, valid_session
        end

        it "assigns the requested event as @event" do
          event = Event.create! valid_attributes
          put :update, {:id => event.to_param, :event => valid_attributes}, valid_session
          expect(assigns(:event)).to eq(event)
        end

        it "redirects to the event" do
          event = Event.create! valid_attributes
          put :update, {:id => event.to_param, :event => valid_attributes}, valid_session
          expect(response).to redirect_to(event)
        end
      end

      describe "with invalid params" do
        it "assigns the event as @event" do
          event = Event.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          allow_any_instance_of(Event).to receive(:save).and_return(false)
          put :update, {:id => event.to_param, :event => { "owner" => "invalid value" }}, valid_session
          expect(assigns(:event)).to eq(event)
        end

        it "re-renders the 'edit' template" do
          event = Event.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          allow_any_instance_of(Event).to receive(:save).and_return(false)
          put :update, {:id => event.to_param, :event => { "owner" => "invalid value" }}, valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested event" do
        event = Event.create! valid_attributes
        expect {
          delete :destroy, {:id => event.to_param}, valid_session
        }.to change(Event, :count).by(-1)
      end

      it "redirects to the events list" do
        event = Event.create! valid_attributes
        delete :destroy, {:id => event.to_param}, valid_session
        expect(response).to redirect_to(events_url)
      end
    end
  end
end
